version: '2'

services:

    # Postgres
    postgres:
        build: ./Postgres
        image: biotop/postgres
        volumes:
            - ~/.docker-containers/volumes/postgres/data:/var/lib/postgresql/data

    # MongoDB
    mongodb:
        build: ./MongoDB
        image: biotop/mongodb
        volumes:
            - ~/.docker-containers/volumes/mongodb/data:/data

    # Lets-chat
    letschat:
        build: ./Letschat
        image: biotop/letschat
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        environment:
            - LETSCHAT_XMPP_DOMAIN=example.com
            - LETSCHAT_AVATAR_PROVIDER=http://192.168.11.3/trac/trac-plugin-test/avatar

    # Kallithea
    kallithea:
        build: ./Kallithea
        image: biotop/kallithea
        depends_on:
            - postgres
            - letschat
        volumes:
            - ~/.docker-containers/volumes/kallithea/data:/var/lib/kallithea/data
            - ~/.docker-containers/volumes/kallithea/repos:/var/lib/kallithea/repos
        environment:
            - KALLITHEA_ADMIN_USER=admin
            - KALLITHEA_ADMIN_PASS=admin0
            - KALLITHEA_ADMIN_EMAIL=admin@email.com
            - KALLITHEA_LCB_HOSTNAME=letschat
            - KALLITHEA_LCB_PORT=5000
            - KALLITHEA_LCB_TOKEN=
            - KALLITHEA_LCB_ROOMS=

    # Jenkins slave (program #1)
    jenkins-slave-program-1:
        build: ./Jenkins-slave-program
        image: biotop/jenkins-slave-program
        volumes:
            - ~/.docker-containers/volumes/jenkins-slave-program-1/ssh:/home/jenkins/.ssh

    # Jenkins master
    jenkins-master:
        build: ./Jenkins-master
        image: biotop/jenkins-master
        depends_on:
            - jenkins-slave-program-1
        volumes:
            - ~/.docker-containers/volumes/jenkins-master/jenkins_home:/var/jenkins_home

    # Janus-gateway
    janus:
        build: ./Janus
        image: biotop/janus
        volumes:
            - ~/.docker-containers/volumes/certs:/usr/share/certs

    # Trac
    trac:
        build: ./Trac
        image: biotop/trac
        depends_on:
            - letschat
        volumes:
            - ~/.docker-containers/volumes/trac/data:/var/lib/trac
            - ~/.docker-containers/volumes/nginx/www-data:/usr/share/www-data
        environment:
            - TRAC_LCB_HOSTNAME=letschat
            - TRAC_LCB_PORT=5000
            - TRAC_LCB_TOKEN=
            - TRAC_LCB_BLOG_ROOM=blog
            - TRAC_LCB_TICKET_ROOM=ticket
            - TRAC_LCB_WIKI_ROOM=wiki
            - REVERSE_PROXY=192.168.11.3
            - TRAC_PROJECT_NAME=trac-project-sample

    # Errbot
    errbot:
        build: ./Errbot
        image: biotop/errbot
        depends_on:
            - letschat
        volumes:
            - ~/.docker-containers/volumes/errbot/data:/var/lib/errbot/data
            - ~/.docker-containers/volumes/errbot/plugins:/var/lib/errbot/plugins
        environment:
            - ERRBOT_LCB_HOSTNAME=letschat
            - ERRBOT_LCB_TOKEN=
            - ERRBOT_LCB_ROOMS=
            - ERRBOT_LCB_ADMINS=@ktakahashi
            - ERRBOT_LCB_NAME=errbot

    # Reverse-proxy
    nginx:
        build: ./Nginx
        image: biotop/nginx
        ports:
            - "80:80"
            - "443:443"
            - "8089:8089"
            - "8989:8989"
        depends_on:
            - trac
            - kallithea
            - letschat
            - jenkins-master
            - janus
        volumes:
            - ~/.docker-containers/volumes/certs:/usr/share/certs
            - ~/.docker-containers/volumes/nginx/www-data:/usr/share/www-data
