#
# Let's Chat Settings
#
# See defaults.yml for all available options
#

env: production # development / production

http:
  enable: true
  host: '0.0.0.0'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

files:
  enable: true
  provider: local
  local:
    dir: uploads
  restrictTypes: false

xmpp:
  enable: true
  port: 5222
  domain: YOUR_XMPP_DOMAIN

database:
  uri: mongodb://mongodb/letschat

secrets:
  cookie: secretsauce

auth:
  providers: [reverseproxy, local]
  local:
    enableRegistration: true
  reverseproxy:
    userHeader: 'X-Forwarded-User'

giphy:
  enable: false

i18n:
  locale: ja

rooms:
  private: true

notifications:
  mentionedOnly: true

avatar:
  uri: YOUR_AVATAR_PROVIDER
